apiVersion: v1
kind: Service
metadata:
  name: katchblog
  namespace: katchblog
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: katchblog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: katchblog
  namespace: katchblog
spec: 
  selector:
    matchLabels:
      app: katchblog
  replicas: 1
  template:
    metadata:
      labels:
        app: katchblog
    spec:
      volumes:
      - name: katchblog-storage
        persistentVolumeClaim: 
          claimName: katchblog-claim
      containers:
      - name: katchblog
        image: httpd:2.4
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /usr/local/apache2/htdocs/
            name: katchblog-storage