apiVersion: v1
kind: PersistentVolume
metadata:
  name: katchblog-volume
  namespace: katchblog
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/volumes/katchblog"
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: katchblog-claim
  namespace: katchblog
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi